# Generated by Django 3.1.4 on 2020-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('choice1', models.CharField(max_length=30)),
                ('choice2', models.CharField(max_length=30)),
                ('choice3', models.CharField(max_length=30)),
                ('choice4', models.CharField(max_length=30)),
                ('choice5', models.CharField(max_length=30)),
                ('choice6', models.CharField(max_length=30)),
                ('choice7', models.CharField(max_length=30)),
                ('choice8', models.CharField(max_length=30)),
                ('choice9', models.CharField(max_length=30)),
                ('choice10', models.CharField(max_length=30)),
                ('choice11', models.CharField(max_length=30)),
                ('choice12', models.CharField(max_length=30)),
                ('choice13', models.CharField(max_length=30)),
                ('choice14', models.CharField(max_length=30)),
                ('choice_answer_1', models.BooleanField()),
                ('choice_answer_2', models.BooleanField()),
                ('choice_answer_3', models.BooleanField()),
                ('choice_answer_4', models.BooleanField()),
                ('choice_answer_5', models.BooleanField()),
                ('choice_answer_6', models.BooleanField()),
                ('choice_answer_7', models.BooleanField()),
                ('choice_answer_8', models.BooleanField()),
                ('choice_answer_9', models.BooleanField()),
                ('choice_answer_10', models.BooleanField()),
                ('choice_answer_11', models.BooleanField()),
                ('choice_answer_12', models.BooleanField()),
                ('choice_answer_13', models.BooleanField()),
                ('choice_answer_14', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
