# Generated by Django 3.1.4 on 2020-12-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app_script', '0007_question_valid_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='valid_choice',
        ),
    ]
