# Generated by Django 3.1.4 on 2020-12-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app_script', '0008_remove_question_valid_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_count',
            field=models.IntegerField(default=2),
        ),
    ]
