# Generated by Django 3.1.4 on 2020-12-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app_script', '0009_question_choice_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_count',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
