# Generated by Django 3.1.4 on 2020-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app_script', '0011_auto_20201207_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
