# Generated by Django 3.1.4 on 2020-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app_script', '0013_auto_20201207_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice10',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice11',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice12',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice13',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice14',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice5',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice6',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice7',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice8',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice9',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
