# Generated by Django 3.1.4 on 2020-12-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app_script', '0015_auto_20201207_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.TextField(max_length=500),
        ),
    ]
